# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"g\n\x0fInventoryRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08key_name\x18\x02 \x01(\t\x12\x11\n\tkey_value\x18\x03 \x01(\t\x12\x10\n\x08val_name\x18\x04 \x01(\t\x12\x11\n\tval_value\x18\x05 \x01(\t\"\x1f\n\x11SearchByIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x12SearchByIDResponse\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.InventoryRecord\"4\n\rSearchRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\"2\n\x0eSearchResponse\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.InventoryRecord\"V\n\x12SearchRangeRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x17\n\x0fkey_value_start\x18\x02 \x01(\t\x12\x15\n\rkey_value_end\x18\x03 \x01(\t\"8\n\x13SearchRangeResponse\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.InventoryRecord\";\n\x13\x44istributionRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x12\n\npercentile\x18\x02 \x01(\x01\"%\n\x14\x44istributionResponse\x12\r\n\x05value\x18\x01 \x01(\x01\"[\n\rUpdateRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\x12\x10\n\x08val_name\x18\x03 \x01(\t\x12\x13\n\x0bval_val_new\x18\x04 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x92\x02\n\tInventory\x12\x35\n\nSearchByID\x12\x12.SearchByIDRequest\x1a\x13.SearchByIDResponse\x12)\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12\x38\n\x0bSearchRange\x12\x13.SearchRangeRequest\x1a\x14.SearchRangeResponse\x12>\n\x0fGetDistribution\x12\x14.DistributionRequest\x1a\x15.DistributionResponse\x12)\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRECORD']._serialized_start=19
  _globals['_INVENTORYRECORD']._serialized_end=122
  _globals['_SEARCHBYIDREQUEST']._serialized_start=124
  _globals['_SEARCHBYIDREQUEST']._serialized_end=155
  _globals['_SEARCHBYIDRESPONSE']._serialized_start=157
  _globals['_SEARCHBYIDRESPONSE']._serialized_end=211
  _globals['_SEARCHREQUEST']._serialized_start=213
  _globals['_SEARCHREQUEST']._serialized_end=265
  _globals['_SEARCHRESPONSE']._serialized_start=267
  _globals['_SEARCHRESPONSE']._serialized_end=317
  _globals['_SEARCHRANGEREQUEST']._serialized_start=319
  _globals['_SEARCHRANGEREQUEST']._serialized_end=405
  _globals['_SEARCHRANGERESPONSE']._serialized_start=407
  _globals['_SEARCHRANGERESPONSE']._serialized_end=463
  _globals['_DISTRIBUTIONREQUEST']._serialized_start=465
  _globals['_DISTRIBUTIONREQUEST']._serialized_end=524
  _globals['_DISTRIBUTIONRESPONSE']._serialized_start=526
  _globals['_DISTRIBUTIONRESPONSE']._serialized_end=563
  _globals['_UPDATEREQUEST']._serialized_start=565
  _globals['_UPDATEREQUEST']._serialized_end=656
  _globals['_UPDATERESPONSE']._serialized_start=658
  _globals['_UPDATERESPONSE']._serialized_end=691
  _globals['_INVENTORY']._serialized_start=694
  _globals['_INVENTORY']._serialized_end=968
# @@protoc_insertion_point(module_scope)
